import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { packageRoot } from '../core/paths.js';
import { ensureDir, readJson, writeAtomic, writeJson } from '../core/store.js';
import { pluginTree } from './tree.js';

/**
 * OpenAI plugin for Codex CLI and ChatGPT desktop — one tree, one personal marketplace.
 *
 * The tree carries no node_modules: its hooks call the globally installed `vibe` CLI. vibe 3 copied
 * 300MB into the Codex cache because the whole package was the plugin; here the plugin is only the
 * manifest, the six common skills and the notification hooks.
 */
const SKILL_NAMES = ['vibe', 'vibe-discover', 'vibe-scope', 'vibe-build', 'vibe-prove', 'vibe-handoff'] as const;
export const MARKETPLACE_NAME = 'vibe-local';

export interface PluginPaths {
  home: string;
  tree: string;
  marketplace: string;
}

/** The tree lives under ~/.config/vibe so that `.vibe/` keeps one meaning: a project's records. ≤ 4.1.7 put it at ~/.vibe/plugin. */
export function pluginPaths(home: string = os.homedir()): PluginPaths {
  return {
    home,
    tree: path.join(home, '.config', 'vibe', 'plugin', 'vibe'),
    marketplace: path.join(home, '.agents', 'plugins', 'marketplace.json'),
  };
}

/** Remove the ≤ 4.1.7 store at ~/.vibe/plugin, and ~/.vibe itself once empty, so the home never looks like a project. */
export function sweepLegacyPluginStore(home: string = os.homedir()): string[] {
  const legacy = path.join(home, '.vibe', 'plugin');
  if (!fs.existsSync(legacy)) return [];
  fs.rmSync(legacy, { recursive: true, force: true });
  const removed = [legacy];
  const dotVibe = path.join(home, '.vibe');
  if (fs.readdirSync(dotVibe).length === 0) {
    fs.rmSync(dotVibe, { recursive: true, force: true });
    removed.push(dotVibe);
  }
  return removed;
}

/** Language packs shipped next to the six: `skills/antislop-*`, each with `reviewers/<lang>/` prompts. */
export function languagePacks(): string[] {
  const dir = path.join(packageRoot(), 'skills');
  return fs.existsSync(dir) ? fs.readdirSync(dir).filter((n) => n.startsWith('antislop-')).sort() : [];
}

const FENCE = '"'.repeat(3);

function tomlString(text: string): string {
  const escaped = text.replace(/\\/g, '\\\\').replace(new RegExp(FENCE, 'g'), '\\"\\"\\"');
  return [FENCE, escaped, FENCE].join('\n');
}

/** Codex reads custom agents as TOML (name · description · developer_instructions); one per reviewer prompt. */
export function codexAgentToml(lang: string, stage: string): string | null {
  const file = path.join(packageRoot(), 'reviewers', lang, `${stage}.md`);
  if (!fs.existsSync(file)) return null;
  const body = fs.readFileSync(file, 'utf-8').trim();
  const role = stage === 'copy-editor' ? 'first-pass copy editor' : 'second-pass chief editor';
  return `# Generated by vibe from reviewers/${lang}/${stage}.md — the ${lang} ${role} of the antislop-${lang} pack.\nname = "${lang}-${stage}"\ndescription = "antislop-${lang} ${role}: judges a submitted manuscript and returns only PASS or a REJECT list; never rewrites."\ndeveloper_instructions = ${tomlString(body)}\n`;
}

function packageVersion(): string {
  return readJson<{ version: string }>(path.join(packageRoot(), 'package.json'))?.version ?? '0.0.0';
}

/** Rebuild the tree from scratch — a stale file in the cache is worse than a slow install. */
export function assemblePlugin(tree: string): string[] {
  fs.rmSync(tree, { recursive: true, force: true });
  ensureDir(tree);
  const written: string[] = [];
  const version = packageVersion();
  const generated = pluginTree();
  writeAtomic(path.join(tree, '.codex-plugin', 'plugin.json'), generated['.codex-plugin/plugin.json']!);
  written.push('.codex-plugin/plugin.json');
  for (const name of [...SKILL_NAMES, ...languagePacks()]) {
    const from = path.join(packageRoot(), 'skills', name);
    if (!fs.existsSync(from)) continue;
    fs.cpSync(from, path.join(tree, 'skills', name), { recursive: true });
    written.push(`skills/${name}`);
  }
  for (const pack of languagePacks()) {
    const lang = pack.replace('antislop-', '');
    for (const stage of ['copy-editor', 'chief-editor']) {
      const toml = codexAgentToml(lang, stage);
      if (!toml) continue;
      writeAtomic(path.join(tree, 'agents', `${lang}-${stage}.toml`), toml);
      written.push(`agents/${lang}-${stage}.toml`);
    }
  }
  writeAtomic(path.join(tree, 'hooks', 'codex-hooks.json'), generated['hooks/codex-hooks.json']!);
  written.push('hooks/codex-hooks.json');
  for (const file of ['notify.js', 'session.js']) {
    fs.copyFileSync(path.join(packageRoot(), 'hooks', file), path.join(tree, 'hooks', file));
    written.push(`hooks/${file}`);
  }
  fs.writeFileSync(path.join(tree, 'README.md'), `# vibe ${version}\n\nAssembled by \`vibe plugin install\`. Do not edit — rerun the command instead.\nHooks call the globally installed \`vibe\` CLI; the verdict is always \`vibe check\`.\n`, 'utf-8');
  written.push('README.md');
  return written;
}

interface MarketplaceDoc {
  name?: string;
  interface?: unknown;
  plugins?: Array<{ name?: string; [key: string]: unknown }>;
}

/** Register the tree in the personal marketplace Codex and ChatGPT desktop both read. Other plugins are kept. */
export function writeMarketplace(paths: PluginPaths): { file: string; marketplaceName: string } {
  const doc: MarketplaceDoc = readJson<MarketplaceDoc>(paths.marketplace) ?? {};
  doc.name ??= MARKETPLACE_NAME;
  doc.interface ??= { displayName: 'Vibe (local)' };
  const plugins = Array.isArray(doc.plugins) ? doc.plugins : [];
  const entry = {
    name: 'vibe',
    source: { source: 'local', path: `./${path.relative(paths.home, paths.tree).replace(/\\/g, '/')}` },
    policy: { installation: 'AVAILABLE', authentication: 'ON_INSTALL' },
    category: 'Developer Tools',
  };
  const index = plugins.findIndex((p) => p?.name === 'vibe');
  if (index === -1) plugins.push(entry);
  else plugins[index] = entry;
  doc.plugins = plugins;
  writeJson(paths.marketplace, doc);
  return { file: paths.marketplace, marketplaceName: doc.name };
}

export interface PluginInstallReport {
  tree: string;
  marketplace: string;
  marketplaceName: string;
  files: string[];
  version: string;
  next: string[];
}

export function installPlugin(home?: string): PluginInstallReport {
  const paths = pluginPaths(home);
  sweepLegacyPluginStore(paths.home);
  const files = assemblePlugin(paths.tree);
  const { marketplaceName } = writeMarketplace(paths);
  return {
    tree: paths.tree,
    marketplace: paths.marketplace,
    marketplaceName,
    files,
    version: packageVersion(),
    next: [
      `codex plugin marketplace add ${paths.home}`,
      `codex plugin add vibe@${marketplaceName}`,
      'ChatGPT desktop reads the same marketplace file — restart the app to see the plugin',
    ],
  };
}

export interface PluginStatusReport {
  tree: string;
  exists: boolean;
  manifestVersion: string | null;
  packageVersion: string;
  skills: number;
  hooks: boolean;
  registered: boolean;
  drift: string[];
}

export function pluginStatus(home?: string): PluginStatusReport {
  const paths = pluginPaths(home);
  const exists = fs.existsSync(paths.tree);
  const manifestVersion = readJson<{ version?: string }>(path.join(paths.tree, '.codex-plugin', 'plugin.json'))?.version ?? null;
  const version = packageVersion();
  const skillsDir = path.join(paths.tree, 'skills');
  const skills = fs.existsSync(skillsDir) ? fs.readdirSync(skillsDir).filter((n) => n === 'vibe' || n.startsWith('vibe-')).length : 0;
  const hooks = fs.existsSync(path.join(paths.tree, 'hooks', 'codex-hooks.json')) && fs.existsSync(path.join(paths.tree, 'hooks', 'notify.js'));
  const marketplace = readJson<MarketplaceDoc>(paths.marketplace);
  const registered = Boolean(marketplace?.plugins?.some((p) => p?.name === 'vibe'));
  const drift: string[] = [];
  if (!exists) drift.push('plugin tree missing — run `vibe plugin install`');
  if (exists && manifestVersion !== version) drift.push(`manifest ${manifestVersion ?? 'none'} ≠ package ${version}`);
  if (exists && skills !== SKILL_NAMES.length) drift.push(`skills ${skills} ≠ ${SKILL_NAMES.length}`);
  if (exists && !hooks) drift.push('hooks missing');
  if (!registered) drift.push('not registered in the personal marketplace');
  return { tree: paths.tree, exists, manifestVersion, packageVersion: version, skills, hooks, registered, drift };
}
