#!/usr/bin/env node
/**
 * gen-skill-docs.ts — 스킬 카탈로그 자동 생성
 *
 * constants.ts의 매핑 데이터를 읽어 SKILL-CATALOG.md를 생성합니다.
 * - --dry-run: 변경 사항만 확인 (CI용)
 * - --check:   freshness 검증 (stale이면 exit 1)
 *
 * Usage:
 *   npx tsx scripts/gen-skill-docs.ts
 *   npx tsx scripts/gen-skill-docs.ts --check
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SKILLS_DIR = path.join(ROOT, 'skills');
const OUTPUT_FILE = path.join(ROOT, 'SKILL-CATALOG.md');

// ─── constants.ts에서 데이터 임포트 ───

interface SkillFrontmatter {
  name: string;
  description: string;
  triggers?: string[];
  priority?: number;
}

function parseSkillFrontmatter(filePath: string): SkillFrontmatter | null {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (!match) return null;

    const yaml = match[1];
    const name = yaml.match(/name:\s*(.+)/)?.[1]?.trim().replace(/^["']|["']$/g, '') ?? '';
    const description = yaml.match(/description:\s*["'](.+?)["']/)?.[1]
      ?? yaml.match(/description:\s*(.+)/)?.[1]?.trim() ?? '';

    const triggersMatch = yaml.match(/triggers:\s*\[([^\]]*)\]/);
    const triggers = triggersMatch
      ? triggersMatch[1].split(',').map(t => t.trim().replace(/^["']|["']$/g, ''))
      : undefined;

    const priorityMatch = yaml.match(/priority:\s*(\d+)/);
    const priority = priorityMatch ? parseInt(priorityMatch[1], 10) : undefined;

    return { name, description, triggers, priority };
  } catch {
    return null;
  }
}

function loadConstants(): {
  globalSkills: string[];
  stackToSkills: Record<string, string[]>;
  capabilitySkills: Record<string, string[]>;
  stackToLanguage: Record<string, string>;
  stackToExternal: Record<string, string[]>;
} {
  const constantsPath = path.join(ROOT, 'src', 'cli', 'postinstall', 'constants.ts');
  const content = fs.readFileSync(constantsPath, 'utf-8');

  // Parse GLOBAL_SKILLS (core + standard + optional tiers)
  const globalSkills: string[] = [];
  for (const tier of ['GLOBAL_SKILLS_CORE', 'GLOBAL_SKILLS_STANDARD', 'GLOBAL_SKILLS_OPTIONAL']) {
    const tierMatch = content.match(new RegExp(`${tier}[^[]*\\[([\\s\\S]*?)\\]`));
    if (tierMatch) {
      const names = tierMatch[1].match(/'([^']+)'/g)?.map(s => s.replace(/'/g, '')) ?? [];
      globalSkills.push(...names);
    }
  }

  // Parse STACK_TO_SKILLS
  const stackToSkills = parseRecordBlock(content, 'STACK_TO_SKILLS');
  const capabilitySkills = parseRecordBlock(content, 'CAPABILITY_SKILLS');
  const stackToExternal = parseRecordBlock(content, 'STACK_TO_EXTERNAL_SKILLS');

  // Parse STACK_TO_LANGUAGE_FILE
  const langMatch = content.match(/STACK_TO_LANGUAGE_FILE[^{]*\{([\s\S]*?)\};/);
  const stackToLanguage: Record<string, string> = {};
  if (langMatch) {
    const entries = langMatch[1].matchAll(/'([^']+)':\s*'([^']+)'/g);
    for (const entry of entries) {
      stackToLanguage[entry[1]] = entry[2];
    }
  }

  return { globalSkills, stackToSkills, capabilitySkills, stackToLanguage, stackToExternal };
}

function parseRecordBlock(content: string, name: string): Record<string, string[]> {
  const regex = new RegExp(`${name}[^{]*\\{([\\s\\S]*?)\\};`);
  const match = content.match(regex);
  if (!match) return {};

  const result: Record<string, string[]> = {};
  const entries = match[1].matchAll(/'([^']+)':\s*\[([^\]]*)\]/g);
  for (const entry of entries) {
    const key = entry[1];
    const values = entry[2].match(/'([^']+)'/g)?.map(s => s.replace(/'/g, '')) ?? [];
    result[key] = values;
  }
  return result;
}

function discoverAllSkills(): Map<string, SkillFrontmatter> {
  const skills = new Map<string, SkillFrontmatter>();
  if (!fs.existsSync(SKILLS_DIR)) return skills;

  const dirs = fs.readdirSync(SKILLS_DIR, { withFileTypes: true });
  for (const dir of dirs) {
    if (!dir.isDirectory()) continue;
    const skillMd = path.join(SKILLS_DIR, dir.name, 'SKILL.md');
    const fm = parseSkillFrontmatter(skillMd);
    if (fm) skills.set(dir.name, fm);
  }
  return skills;
}

function generateCatalog(): string {
  const { globalSkills, stackToSkills, capabilitySkills, stackToLanguage, stackToExternal } = loadConstants();
  const allSkills = discoverAllSkills();

  const lines: string[] = [];
  const timestamp = new Date().toISOString().split('T')[0];

  lines.push('<!-- AUTO-GENERATED by scripts/gen-skill-docs.ts — DO NOT EDIT MANUALLY -->');
  lines.push(`<!-- Last generated: ${timestamp} -->`);
  lines.push('');
  lines.push('# Vibe Skill Catalog');
  lines.push('');
  lines.push(`> Total: **${allSkills.size} skills** | Global: ${globalSkills.length} | Stack-local: ${new Set(Object.values(stackToSkills).flat()).size} | Capability: ${new Set(Object.values(capabilitySkills).flat()).size}`);
  lines.push('');

  // ─── Global Skills ───
  lines.push('## Global Skills (postinstall → ~/.claude/skills/)');
  lines.push('');
  lines.push('| Skill | Description | Triggers | Priority |');
  lines.push('|-------|-------------|----------|----------|');
  for (const name of globalSkills) {
    const fm = allSkills.get(name);
    const desc = fm?.description ?? '—';
    const triggers = fm?.triggers?.join(', ') ?? '—';
    const priority = fm?.priority ?? '—';
    lines.push(`| \`${name}\` | ${desc} | ${triggers} | ${priority} |`);
  }
  lines.push('');

  // ─── Stack → Skills Routing ───
  lines.push('## Stack → Skills Routing (vibe init/update → .claude/skills/)');
  lines.push('');
  lines.push('| Stack Type | Skills |');
  lines.push('|------------|--------|');
  for (const [stack, skills] of Object.entries(stackToSkills)) {
    lines.push(`| \`${stack}\` | ${skills.map(s => `\`${s}\``).join(', ')} |`);
  }
  lines.push('');

  // ─── Capability → Skills Routing ───
  lines.push('## Capability → Skills Routing');
  lines.push('');
  lines.push('| Capability | Skills |');
  lines.push('|------------|--------|');
  for (const [cap, skills] of Object.entries(capabilitySkills)) {
    lines.push(`| \`${cap}\` | ${skills.map(s => `\`${s}\``).join(', ')} |`);
  }
  lines.push('');

  // ─── External Skills ───
  if (Object.keys(stackToExternal).length > 0) {
    lines.push('## External Skills (skills.sh)');
    lines.push('');
    lines.push('| Stack Type | External Package |');
    lines.push('|------------|-----------------|');
    for (const [stack, skills] of Object.entries(stackToExternal)) {
      lines.push(`| \`${stack}\` | ${skills.map(s => `\`${s}\``).join(', ')} |`);
    }
    lines.push('');
  }

  // ─── Stack → Language Rules ───
  lines.push('## Stack → Language Rules');
  lines.push('');
  lines.push('| Stack Type | Language Rule File |');
  lines.push('|------------|--------------------|');
  for (const [stack, file] of Object.entries(stackToLanguage)) {
    lines.push(`| \`${stack}\` | \`${file}\` |`);
  }
  lines.push('');

  // ─── All Skills Detail ───
  lines.push('## All Skills (Alphabetical)');
  lines.push('');
  const sorted = [...allSkills.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  for (const [name, fm] of sorted) {
    const scope = globalSkills.includes(name)
      ? 'global'
      : Object.values(stackToSkills).flat().includes(name)
        ? 'stack-local'
        : Object.values(capabilitySkills).flat().includes(name)
          ? 'capability'
          : 'unrouted';
    lines.push(`### \`${name}\` (${scope})`);
    lines.push('');
    lines.push(`- **Description**: ${fm.description}`);
    if (fm.triggers) lines.push(`- **Triggers**: ${fm.triggers.join(', ')}`);
    if (fm.priority) lines.push(`- **Priority**: ${fm.priority}`);
    lines.push('');
  }

  return lines.join('\n');
}

// ─── Main ───

function main(): void {
  const args = process.argv.slice(2);
  const isDryRun = args.includes('--dry-run');
  const isCheck = args.includes('--check');

  const generated = generateCatalog();

  if (isDryRun) {
    process.stdout.write(generated);
    return;
  }

  if (isCheck) {
    if (!fs.existsSync(OUTPUT_FILE)) {
      console.error('STALE: SKILL-CATALOG.md does not exist. Run: npx tsx scripts/gen-skill-docs.ts');
      process.exit(1);
    }
    const existing = fs.readFileSync(OUTPUT_FILE, 'utf-8');
    // Compare ignoring timestamp line
    const normalize = (s: string): string => s.replace(/<!-- Last generated: .* -->/, '').trim();
    if (normalize(existing) !== normalize(generated)) {
      console.error('STALE: SKILL-CATALOG.md is out of date. Run: npx tsx scripts/gen-skill-docs.ts');
      process.exit(1);
    }
    console.log('FRESH: SKILL-CATALOG.md is up to date.');
    return;
  }

  fs.writeFileSync(OUTPUT_FILE, generated);
  console.log(`Generated ${OUTPUT_FILE} (${generated.split('\n').length} lines)`);
}

main();
