import assert from 'node:assert/strict';
import fs from 'node:fs';
const card = fs.readFileSync(new URL('../card.md', import.meta.url), 'utf8');
const delivery = fs.readFileSync(new URL('../internal/guides/delivery.md', import.meta.url), 'utf8');
assert.match(card, /what changed/);
assert.match(card, /what was verified/);
assert.match(card, /unknown/);
assert.match(delivery, /user acceptance/);
assert.match(delivery, /business value/);
console.log('report guidance separates delivered behavior, verification and business value');
